### ISSUE TITLE
Fails to detect installed debian codename on bullseye

### ISSUE THREAD

**Issue by stbuehler** [AMD1212/check_debsecan#1]
```
$ grep "PRETTY_NAME" /etc/os-release | cut -d "(" -f 2 | cut -d ")" -f 1
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
```

Imho the proper way would be:
```
$ lsb_release -sc
bullseye
```

**Comment by AMD1212** [comment]
Hello,

Thanks for the recomendation. Now switched from my grep magic to lsb_release.
In the first place I've tried to avoid the use because it would be an additional dependency for the check. lsb_release is not by default installed on any Debian setups.

But as most of the other monitoring checks depend on lsb_release as well, it makes no sense to work around a simple dependency.

Thanks
best regards
